### PR TITLE
fixes grammar on thank_you gift_next_body

### PR DESCRIPTION
**Pull request by DerangedMind**
Small fix. `your` to `you're`

### CODE REVIEW

**Comment by Two-Finger** [comment]
This typo is in most of the other locale files, too.
And there's another typo on the same line - 'notifing' (also in the other locales).

**Comment by rakvat** [comment]
@Two-Finger thank you for the hint! @DerangedMind do you want to fix those too before merging?

**Comment by johnbaku** [comment]
@Two-Finger thanks!

**Comment by DerangedMind** [comment]
Perfect. Thanks @Two-Finger. I've made the changes. 😸

**Pull request merged**
