### PR TITLE
[FR] Correction of sentence form in French contact form

### PR DESCRIPTION
**Pull request by erickgirard**
Correction of the sentense. "Nous vous reviendrons" should be said instead of "nous reviendrons vers vous"

### CODE REVIEW

**Comment by lucsurr** [comment]
I might be wrong, but as a natural French speaker I fully disagree here, those do not have the same meaning at all. “Revenir vers quelqu’un” is an expression, meaning that [you are going to contact someone (again)](http://dictionnaire.reverso.net/francais-definition/revenir%20vers%20qqn), while “nous vous reviendrons” means to (physically) come back to you, even with a notion of property, or at least of strong relation, between “nous” and “vous”…

**Comment by yianni3000** [comment]
@erickgirard thank you very very much for the help! I will have to agree with @lucsurr here.

**Comment by johnbaku** [comment]
Just for perspective... @erickgirard and @lucsurr... is one of you from Quebec and the other from France by any chance? And is it more of a dialect thing?

**Comment by erickgirard** [comment]
I'm from Quebec and always used the French as my primary language. It could explain the differences of formulations between me & @lucsurr indeed. 

I guess we could make it more international if we go by "nous vous contacterons" instead?

**Comment by reneklacan** [comment]
Looks like we should have two french locales 😆

**Comment by johnbaku** [comment]
@erickgirard @lucsurr I wonder if sites usually have separate translations for Quebec and France?

At quick glance:

- Facebook has one French (France) and French (Quebec) as two different options.
- Twitter just has one French.

@erickgirard and @lucsurr based on your experience with the French translation is there a couple places which would benefit from having different versions of French... one for Quebec and one for France?

I went to French school in Quebec but I was taught allegedly French from France so what do I know... I also was the worse at French in the whole school! :-/

**Comment by johnbaku** [comment]
We had "Points D'Anglais" when I was in school... you speak English you get a "Point D'Anglais"... for every 3 you get a Retenue... I had the school record for Retenues! :-p

**Comment by erickgirard** [comment]
@johnbaku adding more locales would add to the burden of maintaining such files, it's mostly up to you. 

I would rather suggest that you target international french first, and see after maybe if you want to pimp it for France or Québec. As much as I'm a vocal québécois-french defender, there are still other varieties of french in the world (https://fr.wikipedia.org/wiki/Fran%C3%A7ais#/media/File:Dialectes_de_la_langue_fran%C3%A7aise.png) targetting the international french would lessen the "weirdness" (for a lack of better word).

**Comment by lucsurr** [comment]
Eh, yep, I’m from France :)

I’d follow @erickgirard here. I’m pretty sure we can find some reasonably international French compromise, actually having people from different variants should precisely help us avoiding usage of stuff specific to a given variant ;)

**Comment by lucsurr** [comment]
PS: would rather say “nous vous recontacterons”  then :tongue:

**Comment by erickgirard** [comment]
@lucsurr good point! I like it and changed my pull request in that direction.

**Pull request merged**
