### PR TITLE
Proofread German locale file

### PR DESCRIPTION
**Pull request by rbq**
Went through the German locale and fixed some stuff.

### CODE REVIEW

**Comment by rakvat** [comment]
@rbq thank you very much for your contribution! 

We chose capitalization for words in titles and on buttons. That why it is `Wieder Starten` instead of `Wieder starten`. Otherwise your changes look good!

Thank you again!

**Comment by rbq** [comment]
Oh, okay. But why not put the correct spelling into the locales files and use CSS for presentational purposes? Should be less confusing for translators and improve reusability of strings.

```css
h1, h2, h3, h4, h5, h6, input[type="button"], input[type="submit"] {
  text-transform: capitalize;
}
```

**Comment by joaocunha** [comment]
@rbq `text-transform` can be hurt certain locales. It's not localization friendly.

**Comment by rakvat** [comment]
@rbq thank you again!

**Comment by rbq** [comment]
I reverted everything that looked like it's meant to be capitalized.

@joaocunha Not sure I understand. Capitalizing words against the rules of grammar obviously changes their meaning in any language, doesn't it? E.g. „Willkommen zuhause“ welcomes someone returning home, whereas „Willkommen Zuhause“ is a strange but friendly greeting from someone to their home. „Ich folge“ means “I follow”, but „Ich Folge“ means something like “Me, the sequence, …”. That's why I suggested using correct translations in the first place. ;)

**Comment by rbq** [comment]
You're welcome. :)

**Comment by joaocunha** [comment]
@rbq not sure I understand you too :)

> Oh, okay. But why not put the correct spelling into the locales files and use CSS for presentational purposes?

We are capitalizing the strings by hand so it's predictable. If we leave that job to CSS, it can capitalize the string incorrectly - for example, a Turkish `ì` would become `I` in certain browsers, hence changing the meaning of the word.

You can see a test table here: https://www.w3.org/International/tests/repo/results/text-transform

**Comment by rbq** [comment]
So it changes it into a different letter? Not cool. 😆

What I mean is that in German all nouns are capitalized and lots of words are turned into nouns when you capitalize them, e.g.:

* folgen – to follow / Folgen – the sequences
* zuhause – at home / Zuhause – the home

Capitalisation for decorative purposes might work in English and other languages because the casing barely carries any meaning. In German that's just not the case.

**Comment by joaocunha** [comment]
@rbq ah, I get you. Makes sense, but I'm afraid I'll have to leave _Diese Diskussion_ for you German speakers :P

Thanks a lot for your input and fixes!

**Pull request merged**
