### PR TITLE
Validated hu.yml

### PR DESCRIPTION
**Pull request by kistitan**
To be approved...

### CODE REVIEW

**Comment by joaocunha** [comment]
@kistitan you can self :+1: grammar/spelling changes on languages you're responsible for.

**Comment by kistitan** [comment]
@joaocunha I know... But I got some scolding from @reneklacan that I should not merge by myself :)
So from now I open a PR ;)

The actual issue is that CI uses a different validator that I found online, and does not accept this language file...

**Comment by joaocunha** [comment]
@kistitan wrapping the sentences in quotes wouldn't help?

**Comment by reneklacan** [comment]
@kistitan I just said you shouldn't push directly to master before your PR is passing on CI.... two different things...

**Pull request merged**
