### PR TITLE
Updated texts for Tighten Up Signup Flow #19775

### PR DESCRIPTION
**Pull request by ivanyeoh**
Issue: https://github.com/fetlife/fetlife-web/issues/19775

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
Screenshot 2023-03-03 at 6 03 04 PM
Screenshot 2023-03-03 at 6 02 06 PM

</td>
<td>
Screenshot 2023-03-03 at 5 58 39 PM
Screenshot 2023-03-03 at 5 59 03 PM

</td>
</tr>
</table>

### CODE REVIEW

**Review by nielsenramon — APPROVED** [review]
Mind running the command so all translations have this change please 🙏 @ivanyeoh

**Comment by ivanyeoh** [comment]
@nielsenramon yes sure, I was about to ask if who will translate for other languages?

**Comment by nielsenramon** [comment]
@ivanyeoh For most of them we have translations already, if not, use english!

**Comment by nielsenramon** [comment]
> because the meaning has change, so we should turn those in other languages back in english right?

Correct!

**Pull request merged**
