### PR TITLE
Add new contact locales

### PR DESCRIPTION
**Pull request by nielsenramon**

### CODE REVIEW

**Comment by Two-Finger** [comment]
@rakvat Why not translate "language"?

**Comment by rakvat** [comment]
@Two-Finger if I happen to be on a browser with a language default that I don't understand and language is translated then I'm not able to find the change language option.

**Comment by Two-Finger** [comment]
@rakvat Is FetLife locale tied to browser locale?
I just tried switching my Firefox for Android to German, and nothing changed, even after refreshing the FetLife page.

**Comment by rakvat** [comment]
@Two-Finger the browser locale is used when you did not set your language yet.

**Comment by Two-Finger** [comment]
@rakvat I just found an imperfection about that.
Once fetlife.com has been opened for the first time in a particular browser, FetLife would save the browser preferred language in the cookie and all further changes to this browser setting are ignored.

If a new FetLife user doesn't know that fetlife.com has a link to switch the language, or where it is, she may try to change the preferred language in the browser settings only to find that it does nothing and the site is still in "Greek".

DuckDuckGo, for example, has a "Browser preferred language" option in the languages list.
You can switch the browser setting many times and the site always respects that.
Only if you explicitly select a language from within the site then it takes priority over the browser setting.

**Comment by Two-Finger** [comment]
Also, there's an untranslated "Glossary" link in the sidebar. (The sidebar *after* you're logged in.)

**Pull request merged**
