### PR TITLE
More fixes and 'frenchy' tweaks (guidelines/invitefriend/landing/legalese sections).

### PR DESCRIPTION
**Pull request by lucsurr**
Also added some comments about TODO’s or not-so-good translations…

### CODE REVIEW

**Comment by joaocunha** [comment]
Thanks, @lucsurr!

@yianni3000 may you have a look at this one?

(if approved, comments should be stripped out before merging)

**Comment by lucsurr** [comment]
@joaocunha, you obviously manage your codebase as you like, but any strong reason to strip comments out? I put them here because I thought that was valuable info for other/future translators…

**Comment by joaocunha** [comment]
@lucsurr comments on data files create extra complexity for the parsers, which is always good to avoid. I'd rather move them to GitHub issues. Do you mind?

**Comment by lucsurr** [comment]
@joaocunha Ah makes sense, moving them to GitHub issues sounds good then. :)

**Comment by yianni3000** [comment]
@joaocunha  I have reviewed the changes they look very good. Thanks agaaaaaain @lucsurr ! Did not know what to do about comments :/

**Comment by lucsurr** [comment]
Created [french translation issue](https://github.com/fetlife/translations/issues/46), will update patch to nuke comments now. ;)

**Comment by joaocunha** [comment]
@lucsurr merci beaucoup!

**Comment by johnbaku** [comment]
@joaocunha to be honest I am kind of on the fence, I feel like the comments that @lucsurr made for good discussion in context. But, I also understand why moving them into issues is also a good idea. 

But I don't think we should have a hard in fast rule about leaving comments in the translation file because it makes it easier for the next person who contributes to get context so to not re-invent the wheel or waste there time. Especially when we are trying to get a feel for a specific language.

_P.S. For the longest time I was also going to suggest we add URLs to the translation file to make it easy for people to find the page associated with the section of the YAML file... you know what.. I will add that as an issue! :-p_

**Comment by joaocunha** [comment]
@johnbaku I see where you are coming from. I just think the cons outnumber the pros.

As I posted over Basecamp:

> Comments on data files are usually just noise - stuff that could be either discussed on the Pull Request (style preferences) or converted into actionable GitHub issues (TODOs). That's my motivation for thumbing down comments.

Debating over translations is really common - hardcore enthusiasts/purists could endlessly debate over every single line (and for good reason). That kind of noise is detrimental, not only because it will increase the file size, but because even the comments themselves would have to be tweaked as we fine tune the translations. That kind of information is better stored and discussed over issues, IMO.

Also, having 1:1 number of lines among the files is a positive thing. It's really easy to spot if something went wrong with a merge.

**Comment by joaocunha** [comment]
Moving this discussion to #48.

**Pull request merged**
