### PR TITLE
Add the language of Chinese (Hong Kong)

### PR DESCRIPTION
**Pull request by Jenny-HT**
This pull request serves as providing a starting point for other contributors on Chinese (Hong Kong).

### CODE REVIEW

**Comment by Jenny-HT** [comment]
To resolve #245

**Comment by johnbaku** [comment]
@Jenny-HT great initiative. 

Is there possibly one or two people out there who knows enough "Chinese (Hong Kong)" to review this PR? Would really appreciate it. Thanks.

**Comment by kumo-cloud-fetlife** [comment]
Hi! 852 BDSM would be delighted to give any help! Our group has already finished translation on Glossary page. 
Check out our website at https://852bdsm.com
Our translated glossary at https://852bdsm.com/category/詞彙表-glossary/

**Comment by Jenny-HT** [comment]
@johnbaku Thank you.

To speed up the review process, these are the entries I translated. They are a few but good to start with. :D

- language_name
- login_button
- signup_button
- stats_members

Reviewers, please comment, approve or deny. Thank you in advance.

**Review by NewBBWLover — APPROVED** [review]

**Review by NewBBWLover — APPROVED** [review]
0k

**Comment by Jenny-HT** [comment]
- [ ] Add the missing translation keys. 
- [ ] Add more Chinese (Hong Kong) translations.

**Comment by nielsenramon** [comment]
Closing as it's missing our new strings.

**Pull request closed without merging**
